# Generated by Django 4.2.5 on 2025-10-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mapel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='nama',
        ),
        migrations.AddField(
            model_name='kelas',
            name='nama_kelas',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kelas',
            name='tingkat',
            field=models.CharField(choices=[('1', 'Kelas 1'), ('2', 'Kelas 2'), ('3', 'Kelas 3'), ('4', 'Kelas 4'), ('5', 'Kelas 5'), ('6', 'Kelas 6')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
