# Generated by Django 4.2.5 on 2025-10-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_siswa_alamat_siswa_email_siswa_foto_siswa_nama_ayah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='penerbit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
