# Generated by Django 4.2.5 on 2025-10-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_mapel_penerbit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mapel',
            name='penerbit',
        ),
        migrations.AddField(
            model_name='kelas',
            name='wali_kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wali', to='dashboard.guru'),
        ),
        migrations.AddField(
            model_name='mapel',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.guru'),
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penerbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.penerbit')),
            ],
        ),
        migrations.AddField(
            model_name='mapel',
            name='buku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.buku'),
        ),
    ]
