# Generated by Django 4.2.5 on 2025-10-24 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_penerbit_remove_mapel_penerbit_kelas_wali_kelas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapel',
            name='guru',
        ),
        migrations.CreateModel(
            name='MapelGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.guru')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mapel')),
            ],
            options={
                'unique_together': {('mapel', 'guru')},
            },
        ),
        migrations.CreateModel(
            name='KelasMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mapel')),
            ],
            options={
                'unique_together': {('kelas', 'mapel')},
            },
        ),
        migrations.CreateModel(
            name='KelasGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wali_kelas', models.BooleanField(default=False)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kelas')),
            ],
            options={
                'unique_together': {('kelas', 'guru')},
            },
        ),
    ]
