# Generated by Django 4.2.5 on 2025-10-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='siswa_foto/'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nama_ibu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siswa',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
