# Generated by Django 4.2.5 on 2025-10-08 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to=settings.AUTH_USER_MODEL),
        ),
    ]
